name: Feature request report
description: Use this issue report to propose for a feature or change
title: "[Enhancement issue]: "
labels: ["enhancement"]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement issue report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: enhancement
    attributes:
      label: Proposed change
      placeholder: proposed change
    validations:
      required: true
  - type: textarea
    id: importance
    attributes:
      label: why is it important
      description: Please tell us why the proposed change is needed.
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: Additional context
      description: Add any addtion information that can be used in your proposed change .
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
